name: shared_preferences_example
description: A new Flutter project.

# The version of your app
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15  # Ensure this is in the dependencies section

  # Other dependencies can go here
  # e.g., http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
